hello_world:
  outputs:
    dev:
      type: duckdb
      schema: main
      path: md:dbt_tutorial
      threads: 1
    local:
      type: duckdb
      schema: main
      path: local.duckdb
      threads: 1
  target: dev
